version: '3'

env:
  ROOT_DIR:
    sh: echo $(pwd)
  SCRIPTS_DIR:
    sh: echo $(pwd)/scripts
  LOCALSTACK_VOLUME_DIR:
    sh: echo $(pwd)/.data/localstack

tasks:
  welcome:
    desc: Print a welcome message
    cmds:
      - echo "Welcome to Tizmo! This is your Taskfile. You can define your tasks here."
    silent: true

  install-terraform:
    desc: Install terraform
    cmds:
      - ${SCRIPTS_DIR}/terraform.sh install

  uninstall-terraform:
    desc: Uninstall terraform
    cmds:
      - ${SCRIPTS_DIR}/terraform.sh uninstall

  verify-terraform:
    desc: Verify terraform installation
    cmds:
      - ${SCRIPTS_DIR}/terraform.sh verify

  upgrade-terraform:
    desc: Upgrade terraform to latest version
    cmds:
      - ${SCRIPTS_DIR}/terraform.sh upgrade

  dev:
    desc: Start development server
    cmds:
      - cd apps/web && bun run start

  build:
    desc: Build the application
    cmds:
      - cd apps/web && bun run build

  localstack:start:
    desc: Start LocalStack
    cmds:
      - ${SCRIPTS_DIR}/localstack.sh start

  localstack:stop:
    desc: Stop LocalStack
    cmds:
      - ${SCRIPTS_DIR}/localstack.sh stop

  terraform:
    desc: Manage Terraform (interactive or specify -e and -c)
    cmds:
      - python3 ${SCRIPTS_DIR}/terraform.py -e {{.ENV}} -c {{.COMMAND}}
    env:
      ENV:
      COMMAND:
